# Generated by Django 5.0.dev20230421174959 on 2023-04-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgpt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='chatgpt',
            name='summury',
        ),
    ]
